name: Build, Test, and Publish
# synchronize: update a PR by pushing latest commit to PR branch
on:
  pull_request:
    types: [opened, synchronize]
  push:
      branches: 
        - main

jobs:

  build-test-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - run: |
        /bin/bash run.sh install
        /bin/bash run.sh build
        /bin/bash run.sh publish:test
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip \
    #     pip install pre-commit \
    # - name: Analysing the code with pylint
    #   run: |
    #     pre-commit run --all-files
